### ISSUE TITLE
Typo in script overwrites config file

### ISSUE THREAD

**Issue by n3PH1lim** [RandomNinjaAtk/docker-sonarr-sma#4]
Hi i am testing this container an you have a typo in the script.

with this everytime the container is restarted the config file is overwritten.

See in bold 

if [ ! -f "/config/sma/**config**/autoProcess.ini" ]; then
	cp "/usr/local/sma/config/autoProcess.ini.sample" "/config/sma/autoProcess.ini"
fi

**config** should be not there

**Comment by RandomNinjaAtk** [comment]
Good Catch, when I had initially set it up, I had it in a sub directory... I'll fix it and push some image updates!

**Comment by n3PH1lim** [comment]
perfect ty.

**Comment by RandomNinjaAtk** [comment]
Should be fixed in the next update... images are building now, so check for updates in the next in the next 30+ min and they'll hopefully be ready

**Comment by RandomNinjaAtk** [comment]
@n3PH1lim all updated images should be available, see if that fixes your issue and report back

**Comment by n3PH1lim** [comment]
Works perfectly now. Ty
